name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    paths-ignore:
      - '**.md'
      - app/**

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java env
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Lint
        run: ./gradlew app:lint
        
      - name: Build App
        run: ./gradlew app:assembleRelease -PdefaultApiKey=${{ secrets.DEFAULT_PUBLIC_API_KEY }} -PdefaultEndpointUrl=https://ap.api.fpjs.io

      - name: Save application to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: app/build/outputs/apk/release/*